### ISSUE TITLE
Build troubles

### ISSUE THREAD

**Issue by quickfur** [adamdruppe/terminal-emulator#1]
Finally got around to trying out your terminal emulator... but I'm having trouble compiling it. This is on Linux/64-bit with dmd git HEAD. My compile command is:

```
dmd -I../arsd -I../ -ofterminalemulator *.d
```

where `../arsd` is where I cloned your `arsd` repo. For some reason, `-I../` seemed to be necessary, because somewhere `terminal` is imported without the `arsd` prefix, so both paths are needed.

Anyway, here's what the compiler says:

```
attach.d(267): Error: function arsd.terminalemulatorattachutility.setActiveScreen (Terminal* terminal, ref Session session, int s, bool force = false) is not callable using argument types (Terminal*, Session, ulong, bool)
attach.d(323): Error: cannot implicitly convert expression (read(child.socket.handle(), & buffer, 4096LU)) of type long to int
attach.d(338): Error: cannot implicitly convert expression (bidx) of type ulong to int
attach.d(353): Error: cannot implicitly convert expression (bidx) of type ulong to int
attach.d(615): Error: cannot implicitly convert expression (i) of type ulong to int
attach.d(628): Error: cannot implicitly convert expression (i) of type ulong to int
attach.d(636): Error: cannot implicitly convert expression (idx) of type ulong to int
attach.d(640): Error: cannot implicitly convert expression (session.children.length) of type ulong to int
attach.d(837): Error: cannot implicitly convert expression (ev.pastedText.length) of type ulong to int
attach.d(846): Error: cannot implicitly convert expression (data.length) of type ulong to int
attach.d(856): Error: function arsd.terminalemulatorattachutility.setActiveScreen (Terminal* terminal, ref Session session, int s, bool force = false) is not callable using argument types (Terminal*, Session, ulong)
attach.d(985): Error: cannot implicitly convert expression (s) of type ulong to int
terminalemulator.d(2065): Error: core.sys.posix.unistd.execv at /usr/src/d/druntime/import/core/sys/posix/unistd.d(49) conflicts with std.process.execv at /usr/src/d/phobos/std/process.d(3373)
detachable.d(114): Error: template instance arsd.detachableterminalemulator.detachableMain.startChild!(startup) error instantiating
detachable.d(163): Error: cannot implicitly convert expression (len) of type long to int
terminalemulator.d(2365): Error: cannot implicitly convert expression (write(this.master, cast(const(void)*)data, data.length)) of type long to int
terminalemulator.d(2401): Error: cannot implicitly convert expression (read(fd, & buffer, 4096LU)) of type long to int
terminalemulator.d(2065): Error: core.sys.posix.unistd.execv at /usr/src/d/druntime/import/core/sys/posix/unistd.d(49) conflicts with std.process.execv at /usr/src/d/phobos/std/process.d(3373)
main.d(140): Error: template instance main.main.startChild!(startup) error instantiating
terminalemulator.d(2365): Error: cannot implicitly convert expression (write(this.master, cast(const(void)*)data, data.length)) of type long to int
```

**Comment by adamdruppe** [comment]
On Mon, Jan 05, 2015 at 02:57:45PM -0800, H. S. Teoh wrote:

> attach.d(338): Error: cannot implicitly convert expression (bidx) of type ulong to int

Ah, 64 bit. I'll have to fix those up in a bit.

I pretty much always build 32 bit so these things slip past me.

> terminalemulator.d(2065): Error: core.sys.posix.unistd.execv at /usr/src/d/druntime/import/core/sys/posix/unistd.d(49) conflicts with std.process.execv at /usr/src/d/phobos/std/process.d(3373)

That's not my fault though!

**Comment by adamdruppe** [comment]
Interestingly, a lot of those are arguably signed/unsigned bugs anyway.
I explicitly declared int for a reason, but the unsigned array length
changes size too.

**Comment by adamdruppe** [comment]
Should be fixed now, update both repos and try rebuilding.

Terminal.d's module name is still module terminal; so the missing
arsd. there is expected.

Both terminal and simpledisplay lack the package name for historical
reasons... I offered them as totally standalone plain downloads when I
first announced them, outside of github.

I should probably just go ahead and rename them soon though for consistency.

**Comment by quickfur** [comment]
OK, half the errors are gone now. :-) But it's still complaining about those conflict errors... :-(  And also about not finding `monospace-2.ttf` -- where would that be found? Or would any monospace system font do?

**Comment by adamdruppe** [comment]
> And also about not finding monospace-2.ttf -- where would that be found? 

Oh yikes, I completely forgot I embedded that when posting it. It can be anything, I use the Bitstream Vera Sans monospace ttf from my system but it can be whatever you want..

I'm not getting the conflict, prolly something introduced in some Phobos update. Let me change it based on your errors.......

**Comment by adamdruppe** [comment]
I forgot to commit my Makefile too. Since I hardcode paths to my system on them, unless you happen to have a similar file layout as me they typically won't just work, but at least with the makelfile you can see what I was trying to do. This forms three separate executables so the typical dmd *.d isn't the solution either. Now committed mine so if you fix up the paths for your computer, set up that font (see the note in the readme now) and hit make you should be in business.
