### ISSUE TITLE
Embedding graphics in output (enhancement)

### ISSUE THREAD

**Issue by Laeeth** [adamdruppe/terminal-emulator#3]
Hi Adam.

Suppose I wanted to use this to build something like the qtconsole for Ipython that would allow me to embed images in the terminal output.  (For me, typically a chart).  My idea would be to hook this up to lua so I could conveniently access my various D building blocks to operate on time series and play with the data.

What would be the best way to do this ?

Laeeth

**Comment by adamdruppe** [comment]
On Sat, Sep 19, 2015 at 09:04:14AM -0700, Laeeth Isharc wrote:

> What would be the best way to do this ?

Support for displaying static images is already in there, it
works via a magic output sequence.

The file `utility.d` gives a command line thing to do it too.
See this screenshot for the command and the output:

http://arsdnet.net/terminal-image.png

actually seems to be moderately buggy there, I must have introduced
a regression with some other change. But it basically works for PNG
images at least.

Though, remember this will only work if my terminal is used. You
might actually be better off writing a little GUI program to display
what you need rather than terminal, or do a standard terminal program
that pops up an external image viewer or window for the chart (kinda
like what gnuplot does).

My libs have stuff to do all this. I've started documenting simpledisplay
in more depth http://arsdnet.net/arsd/simpledisplay.html but generally
it is all still work in progress, so don't hesitate to ask me for
some help. I can slap together a demo program for whatever approach
you want to try.

**Comment by Laeeth** [comment]
That's great !  I like idea of displaying inline otherwise you have charts all over the place (or else you can't scroll up and see history).  Idea is for use in interactive exploration of financial data.  I haven't yet decided if I am stupid for contemplating this over just going with Jupyter/qtconsole.  But with another framework you spend so long trying to understand it before you can do things.

I guess embedding interactive html with javascript within terminal is lots of work for not so much gain ?  Eg so you can click on data point.  So at that point you may as well make a native gui app.

Appreciate your work and the quick reply.

Laeeth.

**Comment by adamdruppe** [comment]
Yeah, going full-blown html + javascript would be hard. But we could pretty easily support click events and forward them to a script language and then draw images. We are really talking native gui app but it would be one that you could extend with your other things easily enough.

**Comment by Laeeth** [comment]
This is really great btw - just tried it now.

Did you ever think about making dub packages for your work - either as a main sourceLibrary with another example package.  Or chopping it up into mini libraries?  People are lazy, and if they can just bring it in via dub more people might use it.  I think, anyway.

Window doesn't like it when you resize it bigger after there is content in the terminal.  First of all you lose existing text in window.  Secondly, if you resize it bigger on open then the first call to utility displayImage works, but after some more calls (might be some==1)  it stops working (you just have a blank space where the image should be.  If you resize it bigger after the terminal is already displaying a picture then it stops working blank immediately (blank space where image).

Click events might be quite handy.  I need to finish some other things before doing much here.  First of all refactoring historical database so works properly with different kinds of price bars and different horizons.  Then trying to wrap templated structs in a tagged union and wrapping the templated functions that operate on the structs so I can call from Lua.  But this is very nice for quick and dirty exploration.  Somehow I find the context switch disruptive to flow of thought (between shell and browser or qtconsole).

**Comment by adamdruppe** [comment]
On Sat, Sep 19, 2015 at 12:03:03PM -0700, Laeeth Isharc wrote:

> Did you ever think about making dub packages for your work - either as a main sourceLibrary with another example package.  Or chopping it up into mini libraries?  People are lazy, and if they can just bring it in via dub more people might use it.  I think, anyway.

dub is really hard to use and I'm too lazy to try to force it to work for me.

> Window doesn't like it when you resize it bigger after there is content in the terminal.  First of all you lose existing text in window.

I don't see this happening here...

> Secondly, if you resize it bigger on open then the first call to utility displayImage works, but after some more calls (might be some==1)  it stops working (you just have a blank space where the image should be.

But I do see this, I'll look at it. (While I use this as my main
terminal (I'm typing this email right now in one), I've never really
used the inline image thing...)

If you resize it bigger after the terminal is already displaying a picture then it stops working blank immediately (blank space where image).

> Click events might be quite handy.

The terminal.d lib supports them from D, so maybe you can forward
them to your script.

**Comment by Laeeth** [comment]
actually also seems to happen if I keep calling utility (it stops displaying the image and shows just blank space) after a few tries.  This is after changing desiredHeight to 60 and desiredWidth to 120 in main.d and not resizing manually after running.

On one png in particular it choked:

![image](https://cloud.githubusercontent.com/assets/6643582/9977775/ecd59bc4-5f0a-11e5-9921-462ac6c2d57d.png)
![yellencropped](https://cloud.githubusercontent.com/assets/6643582/9977779/fe6cfe72-5f0a-11e5-9aa3-044f3d5eeda0.png)

**Comment by Laeeth** [comment]
It's great that it just works to display stuff inline when you ssh to a remote machine from the terminal.

**Comment by Laeeth** [comment]
"dub is really hard to use and I'm too lazy to try to force it to work for me."
understood.  the SDL is a bit nicer than the json.  I'll make a dub.sdl if you would like when I have time.  if you set it as a sourceLibrary you achieve a similar effect to what you do with manual compilation.

"The terminal.d lib supports them from D, so maybe you can forward
them to your script."

Thanks - I will take a look.

I guess I should be able to cross compile for windows just using wine and windows dmd.

Really appreciate this - thank you.

**Comment by adamdruppe** [comment]
The bug with the image is really weird, it affects whenever the content scrolls. Still looking at it. For Windows, yeah, I use wine for that (I think my makefile shows it, my dmdw command is just shorthand for `wine dmd`) or you can also do it on windows itself. The Windows version of the terminal uses libssh2, I provide a Windows dll somewhere, and connects to a linux box somewhere to actually run the inner program.

My problem with dub isn't the file format really, but that it doesn't support single file projects, which is what my things actually are. I don't want to make a new github just to hold one file. Maybe some subpackage hackery can do it, but I don't really care much about dub to be honest.

**Comment by adamdruppe** [comment]
I think I found the scroll issue! New code pushed up.

**Comment by Laeeth** [comment]
Great!  Tku.  

Moved windows problem report to new ticket

**Comment by Laeeth** [comment]
thanks - that is great.  it works now, although the resizing is a bit clunky (flickering and it doesn't display a large image properly).

and it doesn't like compressed images (crashes on std.zlib.d line 59 with data error) - but that is not the end of the world

however new version has same problem on windows (CreateProcess 2 error)

**Comment by adamdruppe** [comment]
That png you linked should work now with the new png.d fix.

**Comment by Laeeth** [comment]
That's great!  I checked and it works.  Same with the others.   Laeeth
