### ISSUE TITLE
windows problem (under wine) - CreateProcess 2 error

### ISSUE THREAD

**Issue by Laeeth** [adamdruppe/terminal-emulator#4]
New problem - I can compile for windows using wine. pretty cool that UTIL.EXE works under wine when called from your terminal running on linux.

however I cannot get MAIN.EXE to run on windows under wine. whatever I do I get a Create Process 2 error on line 2371 of terminalemulator.d (pre version you just pushed). plink on its own works. the command I am running is main.exe plink.exe -P 1022 laeeth@192.168.0.2 command

where command I have tried /usr/bin/bash and /usr/sbin/serverside
I know serverside isn't needed (you need to update code comments to reflect that), but either way it doesn't work.

I fixed my path and plink runs from anywhere, so that is not it. and I tried specifying the full path to plink.exe above instead of just the program name.

any thoughts?

compilation command is:
dmd -m32 main.d ..\arsd\simpledisplay.d ..\arsd\color.d -debug ..\arsd\stb_truetype.d terminalemulator.d -J. ..\arsd\png.d ..\arsd\bmp.d

**Comment by adamdruppe** [comment]
There's an undocumented required first option... so try something like

main.exe 0 plink.exe [.... rest of plink commands]

That 0 is the font size option. 0 is to use a system font. Non-zero will use the built in ttf thing. (On Windows, 0 prolly looks better)

**Comment by Laeeth** [comment]
That goes a bit better, but still not quite there.  (same if I use 0 or 1).

I have an assertion failure at line 1105 of simpledisplay.d (pulse is null).  It says eventloop doesn't work for windows yet in docs.  So what should my compilation instructions be?  As above?  If so, what am I doing wrong that I have the assert.

Thanks v much.

**Comment by adamdruppe** [comment]
On Sat, Sep 19, 2015 at 04:28:50PM -0700, Laeeth Isharc wrote:

> I have an assertion failure at line 1105 of simpledisplay.d (pulse is null).

Oh fixed, I am changing some simpledisplay stuff right now and
haven't worked all the bugs out yet so there's probably a few
regressions in there. Get the new terminal emulator source now
and it should work.

> It says eventloop doesn't work for windows yet in docs.

eventloop.d doesn't but the Windows version doesn't use it, it
has its own thing.

**Comment by Laeeth** [comment]
Hmm still same problem.  The only file that changed when I pulled arsd and terminal-emulator was main.d in terminal-emulator.

**Comment by Laeeth** [comment]
BTW this works great now - on Windows too.  Thanks for this, Adam.
