### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by triplejam** [adamdruppe/terminal-emulator#9]
The terminal is drawn too slowly to be used at a size higher than the default. 

Why not take advantage of these functions?:
https://tronche.com/gui/x/xlib/graphics/drawing/XDrawRectangles.html
https://www.x.org/releases/X11R7.6/doc/man/man3/XmbDrawText.3.xhtml

**Comment by adamdruppe** [comment]
I doubt the drawing functions themselves would make much of a difference. But if you wanna try and give me a PR, I'll consider it. (though I actually have more speed troubles on Windows than Linux...)

My guess is that the batched updates, or rather looping through the screen buffer to redraw dirty cells is actually at fault. The underlying engine doesn't use scrolling functions like it should.

**Comment by triplejam** [comment]
I don't think I can add anything helpful. It seems to me the whole engine is too all over the place. Everything also seems wrapped too much.
Edit: closed by accident lol

**Comment by adamdruppe** [comment]
Oh well.
